print("회원 정보를 입력하세요")
name = input('이름 : ')
mail = input('메일 : ')
userid = input('ID : ')
userPass = input('password : ')
print("-----------------------------------------------------")
print('TO ', mail)
print('ID 및 비밀번호 확인')
print(name+'고객님 안녕하세요')
print(name+'rhrorsladml ID와 비밀번호는 다음과 같습니다.')
print('ID:', userid)
print('비밀번호:' +userPass)
print('-------------------------------------------------------')
